server:
  port: 8081
  tomcat:
      uri-encoding: UTF-8


spring:
  #数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huodian?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    #url: jdbc:mysql://47.104.172.202:3306/seven?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    ##password: lukeshi@2018
    # Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: ExpendHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-init-sql: SELECT 1
  ### 时间返回格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:s
    time-zone: GMT+8

  ### 指定上传文件的大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


## mybatis plus扫描
mybatis-plus:
  mapperLocations: classpath:/mapping/*.xml
  global-config:
    db-config:
      db-type: mysql



#日志
#是否开启日志
debug: true
#logging.level.* 来具体输出哪些包的日志级别
logging:
  level:
    root: debug
    org:
      springframework:
        web: debug
    com:
      ruantian:
        controller: debug

  #指定日志文件输出地址
  file: /root/seven/admin.log








